twig:
    file_name_pattern: '*.twig'
    form_themes: [ 'bootstrap_5_horizontal_layout.html.twig' ]
    globals:
        covers_directory: 'uploads/covers/'

when@test:
    twig:
        strict_variables: true